config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items
  root 'items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

before_action :find_item, only: [:show ,:edit ,:update, :detroy]

def index
    @item = Item.all.order("created_at DESC")
end

def new
@item = Item.new
end

def show
    @item = Item.find(params[:id])
end

def create
    @item = Item.new(item_params)
    if @item.save
        redirect_to root_path
    else
        render'new'
    end
end

def destroy
@item.destroy
redirect_to root_path
end

def edit
end

def update
   if @item.update(item_params)
      redirect_to item_path(@item)
   else 
       render'edit'
   end   
end

private

def item_params
 params.require(:item).permit(:title, :description)
end

def find_item
@item = Item.find(params[:id])
end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "item" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
<h2> Edit toto items </h2>

<%= render 'form'%>
</div>

app/views/items/index.html.erb
<h1><mark>this is a list of items</mark></h1>
<% @item.each do |item|  %>
<h2> <%= link_to item.title , item %> </h2>
<p> <%= item.description %> </p>
<%end%>

<%= link_to"new item", new_item_path %>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
<h1>new todo list</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="col-md-10 col-md-offset-1">
<h2> <%= @item.title %> </h2>
<p> <%= @item.description %> </p>

<div class="col-md-4 col-md-offset-4">
 <%= link_to'back', root_path  %>
 <%= link_to'edit', edit_item_path(@item)  %>
 <%= link_to'DELETE', item_path(@item), method: :delete, data: {confirm:"are you sure?"}%>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptimes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>